### ISSUE TITLE
Design Icon

### ISSUE THREAD

**Issue by oneSIX** [TeamGFS/GFSClock#22]

**Comment by peterse2** [comment]
I have never made one and don't have photoshop, but would like to try making it.

**Comment by oneSIX** [comment]
would this be reasonable to have three options by the end of the week?

**Comment by seitensei** [comment]
Instead of three complete options, can you run a larger number in sketches? Can we extend this to everyone other than @peterse2, and only she builds the final one?

**Comment by seitensei** [comment]
As a general list of sizes, we'll probably want the icons to adhere to two sets of sizes:
- iOS sizes: https://developer.apple.com/library/content/qa/qa1686/_index.html
- Android sizes: https://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html#size

@peterse2 will likely want to use something like Illustrator, [Sketch](https://www.sketchapp.com/), [Gravit](https://www.gravit.io/), [Affinity Designer](https://affinity.serif.com/en-us/designer/), or as a FOSS option, [Inkscape](https://inkscape.org/en/). Vector assets are preferred for the master, since we can resize without significant quality loss.

**Comment by peterse2** [comment]
I am currently using GIMP.

**Comment by oneSIX** [comment]
GIMP is fine. 👍
