### ISSUE TITLE
Redo Date/Time formats to match API

### ISSUE THREAD

**Issue by seitensei** [TeamGFS/GFSClock#90]
Currently, we use Java Date objects to hold date and time within the PunchModel and to interpret it elsewhere.

Java Date is not a particularly useful tool, but this needs to be converted to either Android Calendar or JodaTime and our input/output stream has to be modified/updated to use the date strings found in the [API Documentation](https://github.com/TeamGFS/GFSClock/wiki/API-Docs). This is a priority issue, and is blocking the ability to query the API for punches.

As this should be a trivial issue, there is no flow.

**Comment by seitensei** [comment]
@peterse2 Please take a look at this and provide input as soon as possible.

**Comment by peterse2** [comment]
If the problem is with converting to and from UTC I would recommend JodaTime. According to my research, it is the most recommended in this situation. "Joda-Time provides a quality replacement for the Java date and time classes. The design allows for multiple calendar systems, while still providing a simple API." Basic on Structure: pluggable mechanism for calendars; subclasses such as GregorianCalendar. 
More detailed example code (Joda-Time 2.3)…
     org.joda.time.DateTime now = new org.joda.time.DateTime(); // Default time zone.
     org.joda.time.DateTime zulu = now.toDateTime( org.joda.time.DateTimeZone.UTC );
Dump to console…
     System.out.println( "Local time in ISO 8601 format: " + now );
     System.out.println( "Same moment in UTC (Zulu): " + zulu );
When run…
     Local time in ISO 8601 format: 2014-01-21T15:34:29.933-08:00
     Same moment in UTC (Zulu): 2014-01-21T23:34:29.933Z

I also did see a few mentions of adding the time zone into the conversion to be helpful.

**Comment by peterse2** [comment]
http://joda-time.sourceforge.net/quickstart.html

**Comment by seitensei** [comment]
Cool, so looking at that output format, and looking at date times in the API docs, would simoly switching to Joda fix that?

**Comment by oneSIX** [comment]
looking into just using Java 8 version of the Calendar api.  [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP)

**Comment by seitensei** [comment]
@oneSIX Good find. Use that.

**Comment by seitensei** [comment]
May not need to be as extensive, since we're switching to Jackson for JSON encoding/decoding

**Comment by oneSIX** [comment]
handled by using Jackson and other previous introduced code.
